config/routes.rb
Rails.application.routes.draw do
  scope path: ApplicationResource.endpoint_namespace,
        defaults: { format: :jsonapi } do
    scope module: "api/v1", as: "api" do
      resources :saved_items

      resources :lend_transactions

      resources :number_sizes

      resources :letter_sizes

      resources :item_types

      resources :items

      resources :closets

      resources :styles

      resources :preferences

      resources :users
    end
    mount VandalUi::Engine, at: "/vandal"
    # your routes go here
  end
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: "preferences#index"
  resources :saved_items
  resources :lend_transactions
  resources :number_sizes
  resources :letter_sizes
  resources :item_types
  resources :items
  resources :closets
  resources :styles
  resources :preferences
  devise_for :users
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/api/v1/lend_transactions_controller.rb
class Api::V1::LendTransactionsController < Api::V1::GraphitiController
  def index
    lend_transactions = LendTransactionResource.all(params)
    respond_with(lend_transactions)
  end

  def show
    lend_transaction = LendTransactionResource.find(params)
    respond_with(lend_transaction)
  end

  def create
    lend_transaction = LendTransactionResource.build(params)

    if lend_transaction.save
      render jsonapi: lend_transaction, status: :created
    else
      render jsonapi_errors: lend_transaction
    end
  end

  def update
    lend_transaction = LendTransactionResource.find(params)

    if lend_transaction.update_attributes
      render jsonapi: lend_transaction
    else
      render jsonapi_errors: lend_transaction
    end
  end

  def destroy
    lend_transaction = LendTransactionResource.find(params)

    if lend_transaction.destroy
      render jsonapi: { meta: {} }, status: :ok
    else
      render jsonapi_errors: lend_transaction
    end
  end
end

app/controllers/lend_transactions_controller.rb
class LendTransactionsController < ApplicationController
  before_action :current_user_must_be_lend_transaction_user_lending,
                only: %i[edit update destroy]

  before_action :current_user_must_be_lend_transaction_lender,
                only: %i[edit update destroy]

  before_action :set_lend_transaction, only: %i[show edit update destroy]

  def index
    @q = current_user.items_borrowed.ransack(params[:q])
    @lend_transactions = @q.result(distinct: true).includes(:lender,
                                                            :user_lending, :item).page(params[:page]).per(10)
  end

  def show; end

  def new
    @lend_transaction = LendTransaction.new
  end

  def edit; end

  def create
    @lend_transaction = LendTransaction.new(lend_transaction_params)

    if @lend_transaction.save
      message = "LendTransaction was successfully created."
      if Rails.application.routes.recognize_path(request.referer)[:controller] != Rails.application.routes.recognize_path(request.path)[:controller]
        redirect_back fallback_location: request.referer, notice: message
      else
        redirect_to @lend_transaction, notice: message
      end
    else
      render :new
    end
  end

  def update
    if @lend_transaction.update(lend_transaction_params)
      redirect_to @lend_transaction,
                  notice: "Lend transaction was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @lend_transaction.destroy
    message = "LendTransaction was successfully deleted."
    if Rails.application.routes.recognize_path(request.referer)[:controller] != Rails.application.routes.recognize_path(request.path)[:controller]
      redirect_back fallback_location: request.referer, notice: message
    else
      redirect_to lend_transactions_url, notice: message
    end
  end

  private

  def current_user_must_be_lend_transaction_user_lending
    set_lend_transaction
    unless current_user == @lend_transaction.user_lending
      redirect_back fallback_location: root_path,
                    alert: "You are not authorized for that."
    end
  end

  def current_user_must_be_lend_transaction_lender
    set_lend_transaction
    unless current_user == @lend_transaction.lender
      redirect_back fallback_location: root_path,
                    alert: "You are not authorized for that."
    end
  end

  def set_lend_transaction
    @lend_transaction = LendTransaction.find(params[:id])
  end

  def lend_transaction_params
    params.require(:lend_transaction).permit(:lender_id, :user_lending_id,
                                             :pickup_date_time, :rental_period, :item_id, :chat_history)
  end
end

app/views/lend_transactions/_card.html.erb
<div class="card mb-3">
  <h2 class="card-header h4">
    Lend Transaction #<%= lend_transaction.id %>
  </h2>

  <div class="card-body">
    <dl class="mb-1">
      <dt>Lender</dt>
      <dd>
        <% if @lend_transaction.lender.present? %>
          <%= link_to lend_transaction.lender, lend_transaction.lender %>
        <% end %>
      </dd>

      <dt>User lending</dt>
      <dd>
        <% if @lend_transaction.user_lending.present? %>
          <%= link_to lend_transaction.user_lending, lend_transaction.user_lending %>
        <% end %>
      </dd>

      <dt>Pickup date time</dt>
      <dd><%= lend_transaction.pickup_date_time %></dd>

      <dt>Rental period</dt>
      <dd><%= lend_transaction.rental_period %></dd>

      <dt>Item</dt>
      <dd>
        <% if @lend_transaction.item.present? %>
          <%= link_to lend_transaction.item, lend_transaction.item %>
        <% end %>
      </dd>

      <dt>Chat history</dt>
      <dd><%= lend_transaction.chat_history %></dd>

    </dl>

    <div class="row">
      <div class="col">
        <%= link_to_show_or_back lend_transaction, '<i class="fas fa-search-plus"></i>'.html_safe, '<i class="fas fa-chevron-left"></i>'.html_safe, class: "btn btn-block btn-outline-secondary" %>
      </div>

      <div class="col">
        <% if current_user == @lend_transaction.user_lending %>
          <%= link_to edit_lend_transaction_url(lend_transaction), class: "btn btn-block btn-sm btn-outline-secondary" do %>
            <i class="fas fa-edit"></i>
          <% end %>
        <% end %>
      </div>

      <div class="col">
        <% if current_user == @lend_transaction.user_lending %>
          <%= link_to lend_transaction, method: :delete, data: { confirm: "Do you really want to delete this lend_transaction?" }, class: "btn btn-block btn-outline-secondary" do %>
            <i class="fas fa-trash-alt"></i>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>

  <div class="card-footer text-muted">
    Last updated <%= time_ago_in_words(lend_transaction.updated_at) %> ago
  </div>
</div>

app/views/lend_transactions/_form.html.erb
<% was_validated = lend_transaction.errors.any? %>

<%= form_with(model: lend_transaction, local: true, novalidate: true, class: "mb-3") do |f| %>
  <%= f.hidden_field :lender_id, value: current_user.id %>
  <%= f.hidden_field :user_lending_id, value: current_user.id %>
  <div class="form-group">
    <% pickup_date_time_class = "form-control" %>
    <% pickup_date_time_was_invalid = lend_transaction.errors.include?(:pickup_date_time) %>

    <% if was_validated %>
      <% if pickup_date_time_was_invalid %>
        <% pickup_date_time_class << " is-invalid" %>
      <% else %>
        <% pickup_date_time_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :pickup_date_time %>
    <%= f.datetime_select :pickup_date_time, class: pickup_date_time_class, placeholder: "Enter pickup date time" %>
    <% if pickup_date_time_was_invalid %>
      <% lend_transaction.errors.full_messages_for(:pickup_date_time).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% rental_period_class = "form-control" %>
    <% rental_period_was_invalid = lend_transaction.errors.include?(:rental_period) %>

    <% if was_validated %>
      <% if rental_period_was_invalid %>
        <% rental_period_class << " is-invalid" %>
      <% else %>
        <% rental_period_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :rental_period %>
    <%= f.time_select :rental_period, class: rental_period_class, placeholder: "Enter rental period" %>
    <% if rental_period_was_invalid %>
      <% lend_transaction.errors.full_messages_for(:rental_period).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% item_class = "form-control" %>
    <% item_was_invalid = lend_transaction.errors.include?(:item) %>

    <% if was_validated %>
      <% if item_was_invalid %>
        <% item_class << " is-invalid" %>
      <% else %>
        <% item_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :item_id %>
    <%= f.collection_select :item_id, Item.all, :id, :to_s, {}, class: "form-control" %>
    <% if item_was_invalid %>
      <% lend_transaction.errors.full_messages_for(:item).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% chat_history_class = "form-control" %>
    <% chat_history_was_invalid = lend_transaction.errors.include?(:chat_history) %>

    <% if was_validated %>
      <% if chat_history_was_invalid %>
        <% chat_history_class << " is-invalid" %>
      <% else %>
        <% chat_history_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :chat_history %>
    <%= f.text_area :chat_history, class: chat_history_class, placeholder: "Enter chat history" %>
    <% if chat_history_was_invalid %>
      <% lend_transaction.errors.full_messages_for(:chat_history).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <%= f.button class: "btn btn-outline-secondary btn-block" %>
<% end %>

app/views/lend_transactions/_lend_transactions_search_form.html.erb
<%= search_form_for @q, :class => collapse_search_form, :id => "lend_transactions_filters" do |f| %>
  <p class="lead">Narrow results:</p>

  <div class="form-group">
    <%= f.label :chat_history_cont, "Chat history contains" %>
    <%= f.text_field :chat_history_cont, :class => "form-control", :placeholder => "Chat history contains" %>
  </div>

  <div class="form-group">
    <%= f.label :rental_period, "Rental period" %>
    <div class="row">
      <div class='col-md-6 mb-1'>
        <div class='input-group date' id='rental_periodgteqPicker' data-target-input="nearest">
          <%= f.text_field :rental_period_gteq, :class => "form-control datetimepicker-input", :placeholder => "Rental period greater than or equal to", :data => {:target => '#rental_periodgteqPicker'} %>
          <div class="input-group-append" data-target='#rental_periodgteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-clock-o"></i></div>
          </div>
          <script type="text/javascript">
            $(function () {
                $('#rental_periodgteqPicker').datetimepicker({
                  format: 'LT'
                });
            });
          </script>
        </div>
      </div>
      <div class='col-md-6'>
        <div class='input-group date' id='rental_periodlteqPicker' data-target-input="nearest">
          <%= f.text_field :rental_period_lteq, :class => "form-control datetimepicker-input", :placeholder => "Rental period less than or equal to", :data => {:target => '#rental_periodlteqPicker'} %>
          <div class="input-group-append" data-target='#rental_periodlteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-clock-o"></i></div>
          </div>
          <script type="text/javascript">
            $(function () {
                $('#rental_periodlteqPicker').datetimepicker({
                  format: 'LT'
                });
            });
          </script>
        </div>
      </div>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :pickup_date_time, "Pickup date time" %>
    <div class="row">
      <div class='col-md-6 mb-1'>
        <div class='input-group date' id='pickup_date_timegteqPicker' data-target-input="nearest">
          <%= f.text_field :pickup_date_time_gteq, :class => "form-control datetimepicker-input", :placeholder => "Pickup date time greater than or equal to", :data => {:target => '#pickup_date_timegteqPicker'} %>
          <div class="input-group-append" data-target='#pickup_date_timegteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>

      <div class='col-md-6'>
        <div class='input-group date' id='pickup_date_timelteqPicker' data-target-input="nearest">
          <%= f.text_field :pickup_date_time_lteq, :class => "form-control datetimepicker-input", :placeholder => "Pickup date time less than or equal to", :data => {:target => '#pickup_date_timelteqPicker'} %>
          <div class="input-group-append" data-target='#pickup_date_timelteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script type="text/javascript">
      $(function () {
          $('#pickup_date_timegteqPicker').datetimepicker({
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#pickup_date_timelteqPicker').datetimepicker({
              useCurrent: false,
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#pickup_date_timegteqPicker').on("dp.change", function (e) {
              $('#pickup_date_timelteqPicker').data("DateTimePicker").minDate(e.date);
          });
          $('#pickup_date_timelteqPicker').on("dp.change", function (e) {
              $('#pickup_date_timegteqPicker').data("DateTimePicker").maxDate(e.date);
          });
      });
  </script>

  <div class="form-group">
    <%= f.label :created_at, "Created at" %>
    <div class="row">
      <div class='col-md-6 mb-1'>
        <div class='input-group date' id='created_atgteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_gteq, :class => "form-control datetimepicker-input", :placeholder => "Created at greater than or equal to", :data => {:target => '#created_atgteqPicker'} %>
          <div class="input-group-append" data-target='#created_atgteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>

      <div class='col-md-6'>
        <div class='input-group date' id='created_atlteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_lteq, :class => "form-control datetimepicker-input", :placeholder => "Created at less than or equal to", :data => {:target => '#created_atlteqPicker'} %>
          <div class="input-group-append" data-target='#created_atlteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script type="text/javascript">
      $(function () {
          $('#created_atgteqPicker').datetimepicker({
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atlteqPicker').datetimepicker({
              useCurrent: false,
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atgteqPicker').on("dp.change", function (e) {
              $('#created_atlteqPicker').data("DateTimePicker").minDate(e.date);
          });
          $('#created_atlteqPicker').on("dp.change", function (e) {
              $('#created_atgteqPicker').data("DateTimePicker").maxDate(e.date);
          });
      });
  </script>


  <div class="form-group">
    <%= f.label :lender_email_cont, "Lender email contains" %>
    <%= f.text_field :lender_email_cont, :class => "form-control", :placeholder => "Lender email contains" %>
  </div>

  <div class="form-group">
    <%= f.label :user_lending_email_cont, "User lending email contains" %>
    <%= f.text_field :user_lending_email_cont, :class => "form-control", :placeholder => "User lending email contains" %>
  </div>


  <%= f.submit :class => "btn btn-primary btn-block mb-1" %>

  <a href="/lend_transactions" class="btn btn-outline-secondary btn-block mb-1">Clear filters</a>

<% end %>

<a class="btn btn-outline-secondary btn-block mb-1" data-toggle="collapse" href="#lend_transactions_filters">
  Show filters
</a>

app/views/lend_transactions/_list_item.html.erb
<%= link_to lend_transaction, class: "list-group-item list-group-item-action d-flex align-items-center justify-content-between" do %>
  <div>
    <%= lend_transaction %>
    <small class="text-muted">
      <%= time_ago_in_words(lend_transaction.updated_at) %> ago
    </small>
  </div>

  <span class="btn btn-sm btn-outline-secondary">
    <i class="fas fa-chevron-right fa-fw"></i>
  </span>
<% end %>

app/views/lend_transactions/edit.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        Edit Lend Transaction #<%= @lend_transaction.id %>
      </h2>

      <div class="card-body">
        <%= render "form", lend_transaction: @lend_transaction %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/lend_transactions/index.html.erb
<div class="row mb-3">
  <div class="col-md-12">
    <h1 class="display-4">
      Lend Transactions

      <%= link_to new_lend_transaction_path, class: "btn btn-lg btn-outline-secondary" do %>
        <i class="fas fa-plus fa-fw"></i>
      <% end %>
    </h1>
  </div>
</div>

<div class="row">
  <div class="col-md-12 mb-3">
    <%= render partial: "lend_transactions/lend_transactions_search_form" %>
  </div>
</div>




<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h1 class="card-header h4 d-flex align-items-center justify-content-between">
        Lend Transactions

        <%= link_to new_lend_transaction_path, class: "btn btn-sm btn-outline-secondary" do %>
          <i class="fas fa-plus fa-fw"></i>
        <% end %>
      </h1>

      <div class="list-group list-group-flush">
        <%= render collection: @lend_transactions, partial: "list_item", as: :lend_transaction %>
      </div>
      <div class="card-footer d-flex justify-content-center">
        <%= paginate @lend_transactions, theme: 'twitter-bootstrap-4' %>
      </div>

    </div>
  </div>
</div>

app/views/lend_transactions/new.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        New Lend Transaction
      </h2>

      <div class="card-body">
        <%= render "form", lend_transaction: @lend_transaction %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/lend_transactions/show.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render object: @lend_transaction, partial: "card", as: :lend_transaction %>
  </div>
</div>