config/routes.rb
Rails.application.routes.draw do
  scope path: ApplicationResource.endpoint_namespace,
        defaults: { format: :jsonapi } do
    scope module: "api/v1", as: "api" do
      resources :saved_items

      resources :lend_transactions

      resources :number_sizes

      resources :letter_sizes

      resources :item_types

      resources :items

      resources :closets

      resources :styles

      resources :preferences

      resources :users
    end
    mount VandalUi::Engine, at: "/vandal"
    # your routes go here
  end
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: "preferences#index"
  resources :saved_items
  resources :lend_transactions
  resources :number_sizes
  resources :letter_sizes
  resources :item_types
  resources :items
  resources :closets
  resources :styles
  resources :preferences
  devise_for :users
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/style.rb
class Style < ApplicationRecord
  # Direct associations

  has_many   :preferences,
             dependent: :nullify

  has_many   :items,
             dependent: :nullify

  # Indirect associations

  has_many   :users,
             through: :preferences,
             source: :user

  # Validations

  validates :style_name,
            uniqueness: { message: "This style type already exists" }

  validates :style_name, presence: { message: "Enter new style name" }

  # Scopes

  def to_s
    style_name
  end
end

app/controllers/api/v1/styles_controller.rb
class Api::V1::StylesController < Api::V1::GraphitiController
  def index
    styles = StyleResource.all(params)
    respond_with(styles)
  end

  def show
    style = StyleResource.find(params)
    respond_with(style)
  end

  def create
    style = StyleResource.build(params)

    if style.save
      render jsonapi: style, status: :created
    else
      render jsonapi_errors: style
    end
  end

  def update
    style = StyleResource.find(params)

    if style.update_attributes
      render jsonapi: style
    else
      render jsonapi_errors: style
    end
  end

  def destroy
    style = StyleResource.find(params)

    if style.destroy
      render jsonapi: { meta: {} }, status: :ok
    else
      render jsonapi_errors: style
    end
  end
end

app/controllers/styles_controller.rb
class StylesController < ApplicationController
  before_action :set_style, only: %i[show edit update destroy]

  def index
    @q = Style.ransack(params[:q])
    @styles = @q.result(distinct: true).includes(:items, :preferences,
                                                 :users).page(params[:page]).per(10)
  end

  def show
    @preference = Preference.new
    @item = Item.new
  end

  def new
    @style = Style.new
  end

  def edit; end

  def create
    @style = Style.new(style_params)

    if @style.save
      redirect_to @style, notice: "Style was successfully created."
    else
      render :new
    end
  end

  def update
    if @style.update(style_params)
      redirect_to @style, notice: "Style was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @style.destroy
    redirect_to styles_url, notice: "Style was successfully destroyed."
  end

  private

  def set_style
    @style = Style.find(params[:id])
  end

  def style_params
    params.require(:style).permit(:style_name)
  end
end

app/views/styles/_card.html.erb
<div class="card mb-3">
  <h2 class="card-header h4">
    Style #<%= style.id %>
  </h2>

  <div class="card-body">
    <dl class="mb-1">
      <dt>Style name</dt>
      <dd><%= style.style_name %></dd>

    </dl>

    <div class="row">
      <div class="col">
        <%= link_to_show_or_back style, '<i class="fas fa-search-plus"></i>'.html_safe, '<i class="fas fa-chevron-left"></i>'.html_safe, class: "btn btn-block btn-outline-secondary" %>
      </div>

      <div class="col">
        <%= link_to edit_style_url(style), class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-edit"></i>
        <% end %>
      </div>

      <div class="col">
        <%= link_to style, method: :delete, data: { confirm: "Do you really want to delete this style?" }, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>
      </div>
    </div>
  </div>

  <div class="card-footer text-muted">
    Last updated <%= time_ago_in_words(style.updated_at) %> ago
  </div>
</div>

app/views/styles/_form.html.erb
<% was_validated = style.errors.any? %>

<%= form_with(model: style, local: true, novalidate: true, class: "mb-3") do |f| %>
  <div class="form-group">
    <% style_name_class = "form-control" %>
    <% style_name_was_invalid = style.errors.include?(:style_name) %>

    <% if was_validated %>
      <% if style_name_was_invalid %>
        <% style_name_class << " is-invalid" %>
      <% else %>
        <% style_name_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :style_name %>
    <%= f.text_area :style_name, class: style_name_class, placeholder: "Enter style name" %>
    <% if style_name_was_invalid %>
      <% style.errors.full_messages_for(:style_name).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <%= f.button class: "btn btn-outline-secondary btn-block" %>
<% end %>

app/views/styles/_list_item.html.erb
<%= link_to style, class: "list-group-item list-group-item-action d-flex align-items-center justify-content-between" do %>
  <div>
    <%= style %>
    <small class="text-muted">
      <%= time_ago_in_words(style.updated_at) %> ago
    </small>
  </div>

  <span class="btn btn-sm btn-outline-secondary">
    <i class="fas fa-chevron-right fa-fw"></i>
  </span>
<% end %>

app/views/styles/_style_items.html.erb
<div class="card">
  <div class="card-header d-flex align-items-center justify-content-between">
    Items

    <a data-toggle="collapse" href="#style_items_new_form">
      Add item
    </a>
  </div>

  <ul class="list-group list-group-flush">
    <% @style.items.each do |item| %>
      <li class="list-group-item d-flex align-items-center justify-content-between">
        <%= link_to item, item %>

        <%= link_to item, method: :delete, data: { confirm: "Do you really want to delete this item" } do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>

      </li>
    <% end %>

    <div class="card-footer">
      <div class="collapse" id="style_items_new_form">
        <%= render partial: "styles/style_items_new_form" %>
      </div>
    </div>

  </ul>
</div>

app/views/styles/_style_items_new_form.html.erb
<%= form_with(model: @item, local: true) do |f| %>

  <div class="form-group">
    <%= f.label :closet_id %>

    <%= f.collection_select :closet_id, Closet.all, :id, :to_s, {}, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :item_name %>
    <%= f.text_area :item_name, rows: "3", class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :item_type_id %>

    <%= f.collection_select :item_type_id, ItemType.all, :id, :to_s, {}, class: "form-control" %>
  </div>

  <%= f.hidden_field :style_id, value: @style.id %>

  <div class="form-group">
    <%= f.label :letter_size_id %>

    <%= f.collection_select :letter_size_id, LetterSize.all, :id, :to_s, {}, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :number_size_id %>

    <%= f.collection_select :number_size_id, NumberSize.all, :id, :to_s, {}, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :item_description %>

    <%= f.text_field :item_description, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :photos %>

    <%= f.file_field :photos, class: "form-control" %>
  </div>

  <%= f.submit "Create item", class: "btn btn-block btn-outline-secondary" %>
<% end %>

app/views/styles/_style_preferences.html.erb
<div class="card">
  <div class="card-header d-flex align-items-center justify-content-between">
    Preferences

    <a data-toggle="collapse" href="#style_preferences_new_form">
      Add preference
    </a>
  </div>

  <ul class="list-group list-group-flush">
    <% @style.preferences.each do |preference| %>
      <li class="list-group-item d-flex align-items-center justify-content-between">
        <%= link_to preference, preference %>

        <% if current_user == preference.user %>
          <%= link_to preference, method: :delete do %>
            <i class="fas fa-trash-alt"></i>
          <% end %>
        <% end %>

      </li>
    <% end %>

    <div class="card-footer">
      <div class="collapse" id="style_preferences_new_form">
        <%= render partial: "styles/style_preferences_new_form" %>
      </div>
    </div>

  </ul>
</div>

app/views/styles/_style_preferences_new_form.html.erb
<%= form_with(model: @preference, local: true) do |f| %>

  <%= f.hidden_field :user_id, value: current_user.id %>

  <div class="form-group">
    <%= f.label :number_size_id %>

    <%= f.collection_select :number_size_id, NumberSize.all, :id, :to_s, {}, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :letter_size_id %>

    <%= f.collection_select :letter_size_id, LetterSize.all, :id, :to_s, {}, class: "form-control" %>
  </div>

  <%= f.hidden_field :style_id, value: @style.id %>

  <%= f.submit "Create preference", class: "btn btn-block btn-outline-secondary" %>
<% end %>

app/views/styles/_style_users.html.erb
<div class="card">
  <div class="card-header d-flex align-items-center justify-content-between">
    Users
  </div>

  <ul class="list-group list-group-flush">
    <% @style.users.each do |user| %>
      <li class="list-group-item d-flex align-items-center justify-content-between">
        <a href="/users/<%= user.id %>">
          <%= user %>
        </a>

      </li>
    <% end %>

  </ul>
</div>

app/views/styles/_styles_search_form.html.erb
<%= search_form_for @q, :class => collapse_search_form, :id => "styles_filters" do |f| %>
  <p class="lead">Narrow results:</p>

  <div class="form-group">
    <%= f.label :style_name_cont, "Style name contains" %>
    <%= f.text_field :style_name_cont, :class => "form-control", :placeholder => "Style name contains" %>
  </div>

  <div class="form-group">
    <%= f.label :created_at, "Created at" %>
    <div class="row">
      <div class='col-md-6 mb-1'>
        <div class='input-group date' id='created_atgteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_gteq, :class => "form-control datetimepicker-input", :placeholder => "Created at greater than or equal to", :data => {:target => '#created_atgteqPicker'} %>
          <div class="input-group-append" data-target='#created_atgteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>

      <div class='col-md-6'>
        <div class='input-group date' id='created_atlteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_lteq, :class => "form-control datetimepicker-input", :placeholder => "Created at less than or equal to", :data => {:target => '#created_atlteqPicker'} %>
          <div class="input-group-append" data-target='#created_atlteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script type="text/javascript">
      $(function () {
          $('#created_atgteqPicker').datetimepicker({
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atlteqPicker').datetimepicker({
              useCurrent: false,
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atgteqPicker').on("dp.change", function (e) {
              $('#created_atlteqPicker').data("DateTimePicker").minDate(e.date);
          });
          $('#created_atlteqPicker').on("dp.change", function (e) {
              $('#created_atgteqPicker').data("DateTimePicker").maxDate(e.date);
          });
      });
  </script>


  <div class="form-group">
    <%= f.label :users_email_cont, "Users email contains" %>
    <%= f.text_field :users_email_cont, :class => "form-control", :placeholder => "Users email contains" %>
  </div>


  <%= f.submit :class => "btn btn-primary btn-block mb-1" %>

  <a href="/styles" class="btn btn-outline-secondary btn-block mb-1">Clear filters</a>

<% end %>

<a class="btn btn-outline-secondary btn-block mb-1" data-toggle="collapse" href="#styles_filters">
  Show filters
</a>

app/views/styles/edit.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        Edit Style #<%= @style.id %>
      </h2>

      <div class="card-body">
        <%= render "form", style: @style %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/styles/index.html.erb
<div class="row mb-3">
  <div class="col-md-12">
    <h1 class="display-4">
      Styles

      <%= link_to new_style_path, class: "btn btn-lg btn-outline-secondary" do %>
        <i class="fas fa-plus fa-fw"></i>
      <% end %>
    </h1>
  </div>
</div>

<div class="row">
  <div class="col-md-12 mb-3">
    <%= render partial: "styles/styles_search_form" %>
  </div>
</div>




<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h1 class="card-header h4 d-flex align-items-center justify-content-between">
        Styles

        <%= link_to new_style_path, class: "btn btn-sm btn-outline-secondary" do %>
          <i class="fas fa-plus fa-fw"></i>
        <% end %>
      </h1>

      <div class="list-group list-group-flush">
        <%= render collection: @styles, partial: "list_item", as: :style %>
      </div>
      <div class="card-footer d-flex justify-content-center">
        <%= paginate @styles, theme: 'twitter-bootstrap-4' %>
      </div>

    </div>
  </div>
</div>

app/views/styles/new.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        New Style
      </h2>

      <div class="card-body">
        <%= render "form", style: @style %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/styles/show.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render object: @style, partial: "card", as: :style %>
  </div>
</div>

<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render partial: "styles/style_items" %>
  </div>
</div>

<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render partial: "styles/style_preferences" %>
  </div>
</div>

<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render partial: "styles/style_users" %>
  </div>
</div>