config/routes.rb
Rails.application.routes.draw do
  scope path: ApplicationResource.endpoint_namespace,
        defaults: { format: :jsonapi } do
    scope module: "api/v1", as: "api" do
      resources :saved_items

      resources :lend_transactions

      resources :number_sizes

      resources :letter_sizes

      resources :item_types

      resources :items

      resources :closets

      resources :styles

      resources :preferences

      resources :users
    end
    mount VandalUi::Engine, at: "/vandal"
    # your routes go here
  end
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: "preferences#index"
  resources :saved_items
  resources :lend_transactions
  resources :number_sizes
  resources :letter_sizes
  resources :item_types
  resources :items
  resources :closets
  resources :styles
  resources :preferences
  devise_for :users
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/preference.rb
class Preference < ApplicationRecord
  # Direct associations

  belongs_to :number_size

  belongs_to :letter_size

  belongs_to :style,
             optional: true,
             counter_cache: true

  belongs_to :user

  # Indirect associations

  # Validations

  # Scopes

  def to_s
    user.to_s
  end
end

app/controllers/api/v1/preferences_controller.rb
class Api::V1::PreferencesController < Api::V1::GraphitiController
  def index
    preferences = PreferenceResource.all(params)
    respond_with(preferences)
  end

  def show
    preference = PreferenceResource.find(params)
    respond_with(preference)
  end

  def create
    preference = PreferenceResource.build(params)

    if preference.save
      render jsonapi: preference, status: :created
    else
      render jsonapi_errors: preference
    end
  end

  def update
    preference = PreferenceResource.find(params)

    if preference.update_attributes
      render jsonapi: preference
    else
      render jsonapi_errors: preference
    end
  end

  def destroy
    preference = PreferenceResource.find(params)

    if preference.destroy
      render jsonapi: { meta: {} }, status: :ok
    else
      render jsonapi_errors: preference
    end
  end
end

app/controllers/preferences_controller.rb
class PreferencesController < ApplicationController
  before_action :current_user_must_be_preference_user,
                only: %i[edit update destroy]

  before_action :set_preference, only: %i[show edit update destroy]

  def index
    @q = current_user.preferences.ransack(params[:q])
    @preferences = @q.result(distinct: true).includes(:user, :style,
                                                      :letter_size, :number_size).page(params[:page]).per(10)
  end

  def show; end

  def new
    @preference = Preference.new
  end

  def edit; end

  def create
    @preference = Preference.new(preference_params)

    if @preference.save
      message = "Preference was successfully created."
      if Rails.application.routes.recognize_path(request.referer)[:controller] != Rails.application.routes.recognize_path(request.path)[:controller]
        redirect_back fallback_location: request.referer, notice: message
      else
        redirect_to @preference, notice: message
      end
    else
      render :new
    end
  end

  def update
    if @preference.update(preference_params)
      redirect_to @preference, notice: "Preference was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @preference.destroy
    message = "Preference was successfully deleted."
    if Rails.application.routes.recognize_path(request.referer)[:controller] != Rails.application.routes.recognize_path(request.path)[:controller]
      redirect_back fallback_location: request.referer, notice: message
    else
      redirect_to preferences_url, notice: message
    end
  end

  private

  def current_user_must_be_preference_user
    set_preference
    unless current_user == @preference.user
      redirect_back fallback_location: root_path,
                    alert: "You are not authorized for that."
    end
  end

  def set_preference
    @preference = Preference.find(params[:id])
  end

  def preference_params
    params.require(:preference).permit(:user_id, :number_size_id,
                                       :letter_size_id, :style_id)
  end
end

app/views/preferences/_card.html.erb
<div class="card mb-3">
  <h2 class="card-header h4">
    Preference #<%= preference.id %>
  </h2>

  <div class="card-body">
    <dl class="mb-1">
      <dt>User</dt>
      <dd>
        <% if @preference.user.present? %>
          <%= link_to preference.user, preference.user %>
        <% end %>
      </dd>

      <dt>Number size</dt>
      <dd>
        <% if @preference.number_size.present? %>
          <%= link_to preference.number_size, preference.number_size %>
        <% end %>
      </dd>

      <dt>Letter size</dt>
      <dd>
        <% if @preference.letter_size.present? %>
          <%= link_to preference.letter_size, preference.letter_size %>
        <% end %>
      </dd>

      <dt>Style</dt>
      <dd>
        <% if @preference.style.present? %>
          <%= link_to preference.style, preference.style %>
        <% end %>
      </dd>

    </dl>

    <div class="row">
      <div class="col">
        <%= link_to_show_or_back preference, '<i class="fas fa-search-plus"></i>'.html_safe, '<i class="fas fa-chevron-left"></i>'.html_safe, class: "btn btn-block btn-outline-secondary" %>
      </div>

      <div class="col">
        <% if current_user == @preference.user %>
          <%= link_to edit_preference_url(preference), class: "btn btn-block btn-sm btn-outline-secondary" do %>
            <i class="fas fa-edit"></i>
          <% end %>
        <% end %>
      </div>

      <div class="col">
        <% if current_user == @preference.user %>
          <%= link_to preference, method: :delete, data: { confirm: "Do you really want to delete this preference?" }, class: "btn btn-block btn-outline-secondary" do %>
            <i class="fas fa-trash-alt"></i>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>

  <div class="card-footer text-muted">
    Last updated <%= time_ago_in_words(preference.updated_at) %> ago
  </div>
</div>

app/views/preferences/_form.html.erb
<% was_validated = preference.errors.any? %>

<%= form_with(model: preference, local: true, novalidate: true, class: "mb-3") do |f| %>
  <%= f.hidden_field :user_id, value: current_user.id %>
  <div class="form-group">
    <% number_size_class = "form-control" %>
    <% number_size_was_invalid = preference.errors.include?(:number_size) %>

    <% if was_validated %>
      <% if number_size_was_invalid %>
        <% number_size_class << " is-invalid" %>
      <% else %>
        <% number_size_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :number_size_id %>
    <%= f.collection_select :number_size_id, NumberSize.all, :id, :to_s, {}, class: "form-control" %>
    <% if number_size_was_invalid %>
      <% preference.errors.full_messages_for(:number_size).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% letter_size_class = "form-control" %>
    <% letter_size_was_invalid = preference.errors.include?(:letter_size) %>

    <% if was_validated %>
      <% if letter_size_was_invalid %>
        <% letter_size_class << " is-invalid" %>
      <% else %>
        <% letter_size_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :letter_size_id %>
    <%= f.collection_select :letter_size_id, LetterSize.all, :id, :to_s, {}, class: "form-control" %>
    <% if letter_size_was_invalid %>
      <% preference.errors.full_messages_for(:letter_size).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% style_class = "form-control" %>
    <% style_was_invalid = preference.errors.include?(:style) %>

    <% if was_validated %>
      <% if style_was_invalid %>
        <% style_class << " is-invalid" %>
      <% else %>
        <% style_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :style_id %>
    <%= f.collection_select :style_id, Style.all, :id, :to_s, {}, class: "form-control" %>
    <% if style_was_invalid %>
      <% preference.errors.full_messages_for(:style).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <%= f.button class: "btn btn-outline-secondary btn-block" %>
<% end %>

app/views/preferences/_list_item.html.erb
<%= link_to preference, class: "list-group-item list-group-item-action d-flex align-items-center justify-content-between" do %>
  <div>
    <%= preference %>
    <small class="text-muted">
      <%= time_ago_in_words(preference.updated_at) %> ago
    </small>
  </div>

  <span class="btn btn-sm btn-outline-secondary">
    <i class="fas fa-chevron-right fa-fw"></i>
  </span>
<% end %>

app/views/preferences/_preferences_search_form.html.erb
<%= search_form_for @q, :class => collapse_search_form, :id => "preferences_filters" do |f| %>
  <p class="lead">Narrow results:</p>

  <div class="form-group">
    <%= f.label :created_at, "Created at" %>
    <div class="row">
      <div class='col-md-6 mb-1'>
        <div class='input-group date' id='created_atgteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_gteq, :class => "form-control datetimepicker-input", :placeholder => "Created at greater than or equal to", :data => {:target => '#created_atgteqPicker'} %>
          <div class="input-group-append" data-target='#created_atgteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>

      <div class='col-md-6'>
        <div class='input-group date' id='created_atlteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_lteq, :class => "form-control datetimepicker-input", :placeholder => "Created at less than or equal to", :data => {:target => '#created_atlteqPicker'} %>
          <div class="input-group-append" data-target='#created_atlteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script type="text/javascript">
      $(function () {
          $('#created_atgteqPicker').datetimepicker({
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atlteqPicker').datetimepicker({
              useCurrent: false,
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atgteqPicker').on("dp.change", function (e) {
              $('#created_atlteqPicker').data("DateTimePicker").minDate(e.date);
          });
          $('#created_atlteqPicker').on("dp.change", function (e) {
              $('#created_atgteqPicker').data("DateTimePicker").maxDate(e.date);
          });
      });
  </script>


  <div class="form-group">
    <%= f.label :user_email_cont, "User email contains" %>
    <%= f.text_field :user_email_cont, :class => "form-control", :placeholder => "User email contains" %>
  </div>

  <div class="form-group">
    <%= f.label :style_style_name_cont, "Style style_name contains" %>
    <%= f.text_field :style_style_name_cont, :class => "form-control", :placeholder => "Style style_name contains" %>
  </div>

  <div class="form-group">
    <%= f.label :letter_size_size_cont, "Letter size size contains" %>
    <%= f.text_field :letter_size_size_cont, :class => "form-control", :placeholder => "Letter size size contains" %>
  </div>

  <div class="form-group">
    <%= f.label :size, "NumberSize Size" %>
    <div class="row">
      <div class='col-md-6 mb-1'>
        <%= f.text_field :number_size_size_gteq, :class => "form-control", :placeholder => "NumberSize Size greater than or equal to" %>
      </div>
      <div class='col-md-6'>
        <%= f.text_field :number_size_size_lteq, :class => "form-control", :placeholder => "NumberSize Size less than or equal to" %>
      </div>
    </div>
  </div>


  <%= f.submit :class => "btn btn-primary btn-block mb-1" %>

  <a href="/preferences" class="btn btn-outline-secondary btn-block mb-1">Clear filters</a>

<% end %>

<a class="btn btn-outline-secondary btn-block mb-1" data-toggle="collapse" href="#preferences_filters">
  Show filters
</a>

app/views/preferences/edit.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        Edit Preference #<%= @preference.id %>
      </h2>

      <div class="card-body">
        <%= render "form", preference: @preference %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/preferences/index.html.erb
<div class="row mb-3">
  <div class="col-md-12">
    <h1 class="display-4">
      Preferences

      <%= link_to new_preference_path, class: "btn btn-lg btn-outline-secondary" do %>
        <i class="fas fa-plus fa-fw"></i>
      <% end %>
    </h1>
  </div>
</div>

<div class="row">
  <div class="col-md-12 mb-3">
    <%= render partial: "preferences/preferences_search_form" %>
  </div>
</div>




<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h1 class="card-header h4 d-flex align-items-center justify-content-between">
        Preferences

        <%= link_to new_preference_path, class: "btn btn-sm btn-outline-secondary" do %>
          <i class="fas fa-plus fa-fw"></i>
        <% end %>
      </h1>

      <div class="list-group list-group-flush">
        <%= render collection: @preferences, partial: "list_item", as: :preference %>
      </div>
      <div class="card-footer d-flex justify-content-center">
        <%= paginate @preferences, theme: 'twitter-bootstrap-4' %>
      </div>

    </div>
  </div>
</div>

app/views/preferences/new.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        New Preference
      </h2>

      <div class="card-body">
        <%= render "form", preference: @preference %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/preferences/show.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render object: @preference, partial: "card", as: :preference %>
  </div>
</div>